INSERT INTO roles(name)
SELECT 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ADMIN');

INSERT INTO roles(name)
SELECT 'SELLER'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'SELLER');

INSERT INTO roles(name)
SELECT 'BUYER'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'BUYER');
